---

- name: augenrules
  command: augenrules --load
  when: augenrules_file.stat.exists


- name: restart auditd - suse
  systemd:
      name: auditd
      state: restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        ) and ansible_os_family == "Suse"


- name: restart auditd
  service:
    name: auditd
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        ) and
    not (
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or
        (ansible_os_family == "Suse" )
    ) and
    not augenrules_file.stat.exists

## https://groups.google.com/forum/#!topic/ansible-project/pv1h1Ne7nSk
- name: restart auditd - rhel7
  command: "service auditd restart"
  environment:
    PATH: '/usr/sbin:/usr/bin:/sbin:/bin'
  args:
    warn: False
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        ) and
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) and
    not augenrules_file.stat.exists

- name: restart rsyslog
  service: name=rsyslog state=restarted
